### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by raytopianprojects** [raytopianprojects/CommonFilters#2]
Port

- [ ] MSAA
- [ ] Cartoon Ink
- [ ] Bloom
- [ ] Half Pixel Shift
- [ ] View Glow
- [ ] Volumetric Lighting
- [ ] Ambient Occlusion
- [ ] Gamma Adjust
- [ ] Srgb Encode
- [ ] High Dynamic Range
- [ ] Exposure Adjust

New Filters 
- [ ] Pixelate
- [ ] Half Tone
- [ ] More Tone Mapping
- [ ] LUT/Color Grading
- [ ] VHS?
- [ ] SSGI?
- [ ] SSR
- [ ] Distortion 
- [ ] Tint
- [ ] Deferred Rendering?
- [ ] Non MSAA anti-aliasing (SMAA, TAA,)
- [ ] Add support for using a tri instead of a quad for rendering?
- [ ] Lens Flare
- [ ] PBR Bloom
- [ ] Fog
- [ ] Edge Filtering
- [ ] Grain
- [ ] Depth of Field
- [ ] Dynamic Resolution?

API Questions/Implementation 
- [ ] Does clean up still work?
- [ ] How should adding
- [ ] Preventing new quads from being made every time reconfigure is called
- [ ] What can we leave in reconfigure?
- [ ] Adding consts/globals?
- [ ] Do we need to check if shaders are supported? (Probably for headless and tinypanda)
- [ ] How should adding auxbits work?
- [ ] Convert examples to use new system
